# Generated by Django 3.2.8 on 2022-10-26 21:58

from django.db import migrations
import manager.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='topping_name',
            field=manager.fields.CaseInsensitiveCharField(max_length=100, null=True, unique=True),
        ),
    ]
