# Generated by Django 3.2.8 on 2022-10-28 19:24

from django.db import migrations
import manager.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_auto_20221026_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=manager.fields.CaseInsensitiveCharField(max_length=100, null=True, unique=True),
        ),
    ]
